export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#e2725b",
        "on-background": "#1b1c1c",
        "on-surface": "#1b1c1c",
        "on-secondary-fixed": "#07200f",
        "tertiary": "#605e5a",
        "secondary-container": "#c9e8cb",
        "outline": "#89726d",
        "secondary": "#4a654e",
        "error-container": "#ffdad6",
        "background": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "on-error-container": "#93000a",
        "tertiary-container": "#95928d",
        "primary-fixed": "#ffdad3",
        "surface-container-high": "#eae7e7",
        "surface-container-low": "#f6f3f2",
        "on-surface-variant": "#56423e",
        "on-primary-fixed": "#3e0500",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#1c1c18",
        "surface-variant": "#e4e2e1",
        "outline-variant": "#ddc0ba",
        "on-secondary": "#ffffff",
        "on-primary-container": "#5a0d02",
        "tertiary-fixed-dim": "#c9c6c1",
        "surface-container-highest": "#e4e2e1",
        "inverse-surface": "#303030",
        "tertiary-fixed": "#e6e2dc",
        "surface": "#fcf9f8",
        "secondary-fixed-dim": "#b0ceb2",
        "primary-fixed-dim": "#ffb4a5",
        "secondary-fixed": "#cceace",
        "primary": "#9f402d",
        "on-tertiary-fixed-variant": "#484743",
        "inverse-on-surface": "#f3f0f0",
        "inverse-primary": "#ffb4a5",
        "error": "#ba1a1a",
        "surface-bright": "#fcf9f8",
        "on-tertiary-container": "#2c2b28",
        "on-secondary-fixed-variant": "#334d38",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#4e6952",
        "on-primary-fixed-variant": "#802918",
        "surface-tint": "#9f402d",
        "surface-container": "#f0eded",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "base": "8px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-xl": ["Quicksand"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Quicksand"],
        "headline-lg": ["Quicksand"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Quicksand"],
        "headline-lg-mobile": ["Quicksand"]
      },
      fontSize: {
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "headline-xl-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "30px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
